# Generated by Django 5.0.3 on 2024-05-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='payImage',
            field=models.ImageField(blank=True, null=True, upload_to='payment_method_images/'),
        ),
    ]
